/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package legrafica;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author davox
 */
public class ClientesAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ClientesAdmin
     */
    DefaultTableModel modelo = new DefaultTableModel();
    
    private String emailRegex = "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$";
    private Pattern patternEmail = Pattern.compile(emailRegex, Pattern.CASE_INSENSITIVE);

    public ClientesAdmin() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Clientes");
        llenarTabla();
        
        btnSeleccionar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnAbrirProyecto.setEnabled(false);
        btnCancelar.setEnabled(false);
    }

    private void llenarTabla() {
        Connection con = ConnectDB.getConnection();
        Statement consulta = null;
        if (con != null) {
            try {
                consulta = con.createStatement();
                String nulo = "ninguno";
                ResultSet rs = consulta.executeQuery("Select * FROM cliente");
                modelo.setColumnCount(7);
                modelo.setColumnIdentifiers(new Object[]{"ID", "Usuario", "Nombre", "E-Mail", "Contraseña", "Estado", "Proyecto"});
                while (rs.next()) {
                    int idProyecto = rs.getInt(7);
                    if (idProyecto == 0) {
                        modelo.addRow(new Object[]{ rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), 0});
                    } else {
                        modelo.addRow(new Object[]{ rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getInt(7)});
                    }

                }
            } catch (SQLException ex) {
                Logger.getLogger(ClientesAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }

    private void limpiarCampos() {
        txtIdCliente.setText("");
        txtUsuario.setText("");
        txtNombre.setText("");
        txtEmail.setText("");
        txtContra.setText("");
        radioPotencial.setSelected(true);
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtIdCliente = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        radioPotencial = new javax.swing.JRadioButton();
        radioConProyecto = new javax.swing.JRadioButton();
        radioDeshabilitar = new javax.swing.JRadioButton();
        btnCrear = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtContra = new javax.swing.JTextField();
        btnSeleccionar = new javax.swing.JButton();
        btnAbrirProyecto = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtIdProyecto = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();

        jTable1.setModel(modelo);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarioSelecionado(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        txtIdCliente.setEditable(false);
        txtIdCliente.setBackground(new java.awt.Color(153, 153, 153));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtNombre, org.jdesktop.beansbinding.ObjectProperty.create(), txtUsuario, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtEmail, org.jdesktop.beansbinding.ObjectProperty.create(), txtNombre, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, txtContra, org.jdesktop.beansbinding.ObjectProperty.create(), txtEmail, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        jLabel1.setText("Usuario");

        jLabel2.setText("E-Mail");

        jLabel3.setText("Nombre");

        jLabel4.setText("Estado");

        jLabel6.setText("Id");

        buttonGroup1.add(radioPotencial);
        radioPotencial.setText("Potencial");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, radioConProyecto, org.jdesktop.beansbinding.ObjectProperty.create(), radioPotencial, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        radioPotencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPotencialActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioConProyecto);
        radioConProyecto.setText("Con Proyecto");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, radioDeshabilitar, org.jdesktop.beansbinding.ObjectProperty.create(), radioConProyecto, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        radioConProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioConProyectoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioDeshabilitar);
        radioDeshabilitar.setText("Deshabilitado");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnAbrirProyecto, org.jdesktop.beansbinding.ObjectProperty.create(), radioDeshabilitar, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        radioDeshabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDeshabilitarActionPerformed(evt);
            }
        });

        btnCrear.setBackground(new java.awt.Color(0, 153, 255));
        btnCrear.setText("Crear Cliente");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar Cliente");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnCancelar, org.jdesktop.beansbinding.ObjectProperty.create(), btnModificar, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel7.setText("Contraseña");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, radioPotencial, org.jdesktop.beansbinding.ObjectProperty.create(), txtContra, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        btnSeleccionar.setText("Seleccionar Cliente");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnModificar, org.jdesktop.beansbinding.ObjectProperty.create(), btnSeleccionar, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        btnAbrirProyecto.setText("Abrir Proyecto");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnSeleccionar, org.jdesktop.beansbinding.ObjectProperty.create(), btnAbrirProyecto, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        btnAbrirProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirProyectoActionPerformed(evt);
            }
        });

        jLabel5.setText("Proyecto");

        txtIdProyecto.setEditable(false);
        txtIdProyecto.setUI(null);
        txtIdProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProyectoActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnCrear, org.jdesktop.beansbinding.ObjectProperty.create(), btnCancelar, org.jdesktop.beansbinding.BeanProperty.create("nextFocusableComponent"));
        bindingGroup.addBinding(binding);

        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(txtUsuario)
                                    .addComponent(txtNombre)
                                    .addComponent(txtEmail)
                                    .addComponent(txtContra)))
                            .addComponent(btnSeleccionar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioDeshabilitar)
                                            .addComponent(radioConProyecto)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(radioPotencial)
                                                .addGap(97, 97, 97)
                                                .addComponent(jLabel5)))
                                        .addGap(19, 19, 19)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAbrirProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(txtIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(btnAbrirProyecto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(radioPotencial, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioConProyecto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioDeshabilitar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnModificar)
                    .addComponent(btnSeleccionar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioDeshabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDeshabilitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDeshabilitarActionPerformed

    private void radioPotencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPotencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioPotencialActionPerformed

    private void radioConProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioConProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioConProyectoActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        btnCrear.setEnabled(false);
        btnModificar.setEnabled(true);
        btnCancelar.setEnabled(true);
        
        int fila = jTable1.getSelectedRow();
        txtIdCliente.setText(Integer.toString((Integer) jTable1.getValueAt(fila, 0)));
        txtUsuario.setText((String) jTable1.getValueAt(fila, 1));
        txtNombre.setText((String) jTable1.getValueAt(fila, 2));
        txtEmail.setText((String) jTable1.getValueAt(fila, 3));
        txtContra.setText((String) jTable1.getValueAt(fila, 4));
        txtIdProyecto.setText(Integer.toString((Integer)jTable1.getValueAt(fila, 6)));
        String estado = ((String) jTable1.getValueAt(fila, 5));
        if (estado.equals("potencial")) {
            radioPotencial.setSelected(true);
            btnAbrirProyecto.setEnabled(false);
        }
        if (estado.equals("enProyecto")) {
            radioConProyecto.setSelected(true);
        }
        if (estado.equals("deshabilitado")) {
            radioDeshabilitar.setSelected(true);
            
            btnAbrirProyecto.setEnabled(false);

        }
        
        if(txtIdProyecto.getText().equals("0")){
            btnAbrirProyecto.setEnabled(false);
            radioConProyecto.setEnabled(false);
        }else{
            btnAbrirProyecto.setEnabled(true);
            radioConProyecto.setEnabled(true);
        }

    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        Matcher matcher = patternEmail.matcher(txtEmail.getText());
        String estado = "potencial";
        JDialog frame = new JDialog();
        
        if(radioPotencial.isSelected()) estado = "potencial";
        if(radioConProyecto.isSelected()) estado = "enProyecto";
        if(radioDeshabilitar.isSelected()) estado = "deshabilitado";
        
        if (txtUsuario.getText().equals("") || txtNombre.getText().equals("") || txtEmail.getText().equals("")
                || txtContra.getText().equals("")) {
            JOptionPane.showMessageDialog(frame, "Favor de llenar todos los campos para continuar.");
        } else if(!matcher.matches()){
            JOptionPane.showMessageDialog(frame, "Favor de ingresar un e-mail valido");
        } else {
            try {
                Connection con = ConnectDB.getConnection();
                String sql = "INSERT INTO `cliente` (`id`, `usuario`, `nombre`, `correo_electronico`, `contrasena`, "
                        + "`estado`, `proyecto`) VALUES (NULL, ?, ?, ?, ?, '"+estado+"', NULL);";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, txtUsuario.getText());
                ps.setString(2, txtNombre.getText());
                ps.setString(3, (txtEmail.getText()));
                ps.setString(4, (txtContra.getText()));

                ps.executeUpdate();
                
                limpiarCampos();
                llenarTabla();
            } catch (SQLException ex) {
                Logger.getLogger(ClientesAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        
        Matcher matcher = patternEmail.matcher(txtEmail.getText());
        String estado = "potencial";
        JDialog frame = new JDialog();
        
        if(radioPotencial.isSelected()) estado = "potencial";
        if(radioConProyecto.isSelected()) estado = "enProyecto";
        if(radioDeshabilitar.isSelected()) estado = "deshabilitado";
        
        if (txtUsuario.getText().equals("") || txtNombre.getText().equals("") || txtEmail.getText().equals("")
                || txtContra.getText().equals("")) {
            JOptionPane.showMessageDialog(frame, "Favor de llenar todos los campos para continuar.");
        } else if(!matcher.matches()){
            JOptionPane.showMessageDialog(frame, "Favor de ingresar un e-mail valido");           
        }
        else {
            try {
                Connection con = ConnectDB.getConnection();
                String sql = "UPDATE `cliente` SET `usuario` = ?, `nombre` = ?, `correo_electronico` = ?, `contrasena` = ?, `estado` = ? WHERE `cliente`.`id` = ?; ";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, txtUsuario.getText());
                ps.setString(2, txtNombre.getText());
                ps.setString(3, (txtEmail.getText()));
                ps.setString(4, (txtContra.getText()));
                ps.setString(5, estado);
                ps.setString(6, txtIdCliente.getText());

                ps.executeUpdate();
                
                btnAbrirProyecto.setEnabled(false);
                btnSeleccionar.setEnabled(false);
                btnModificar.setEnabled(false);
                btnCancelar.setEnabled(false);
                btnCrear.setEnabled(true);
                limpiarCampos();
                llenarTabla();
                                
                
            } catch (SQLException ex) {
                Logger.getLogger(ClientesAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAbrirProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirProyectoActionPerformed
        int esteProyecto = Integer.parseInt(txtIdProyecto.getText());
        legrafica.Modelos.Proyectos idProyecto = new legrafica.Modelos.Proyectos();
        idProyecto.setId(esteProyecto);
        FasesAdmin fases =new FasesAdmin(idProyecto);        
        fases.setVisible(true);
    }//GEN-LAST:event_btnAbrirProyectoActionPerformed

    private void txtIdProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProyectoActionPerformed

    private void usuarioSelecionado(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioSelecionado
        btnSeleccionar.setEnabled(true);
    }//GEN-LAST:event_usuarioSelecionado

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCampos();
        llenarTabla();
        btnCrear.setEnabled(true);
        btnSeleccionar.setEnabled(false);
        btnModificar.setEnabled(false);
        btnAbrirProyecto.setEnabled(false);
        btnCancelar.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame ClientesAdmin = new JFrame("Clientes");
                ClientesAdmin.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirProyecto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radioConProyecto;
    private javax.swing.JRadioButton radioDeshabilitar;
    private javax.swing.JRadioButton radioPotencial;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdProyecto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
